### ISSUE TITLE
V1 Location Page - Accessibility Considerations

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#516] opened 2023-12-07 20:32 UTC
### Mac VoiceOver + Chrome
- [ ] Beta Banner: Full website url is read aloud (consider hyperlinking weather.gov)
- [ ] Header: Logo + Weather.gov both have links, duplicative?
- [ ] Search: Redundant "change location" AND "search for location" AND "search for location in search box"
- [ ] Current conditions: doesn’t  have a H2 header
- [ ] Current conditions: Consider skipping to “weather as of [Date][Time] + [Summary]”
- [ ] All Icons don’t have alt text
- [ ] Hourly forecast: navigates by each individual component (4PM, image, mostly cloudy, 2% chance, 46, ºF) should we group these so they're read together by hour?
- [ ] Hourly forecast: I’d like to be able to exit out of Hourly forecast easily and then go to Daily Forecast (without having to tab by component) - wrap in a div? (this might exist in the VO tool / be a possible human error)
- [ ] Hourly forecast: Temperature and ºF are not grouped to be read together
- [ ] Daily forecast: Repetition temperature reads “day will be high of “54” degrees 54º night will be low of 48ºF”

### Chrome Wave Extension
- [ ] No alt text in gov banner for flag
- [ ] Footer links are grouped in multiple <nav> elements with aria labels?

**Comment by greg-does-weather** [comment] 2023-12-08 21:49
It does make sense! I have some thoughts on a few of the items you found, but generally it's a good list to work from.

### Mac VoiceOver + Chrome
- Header: Logo + Weather.gov both have links, duplicative?
  - Ideally they'd be part of the same link, but I don't think we can structure it that way in the HTML. Whether or not there should be two links... I don't really have an opinion. Easy change, either way!
  - Incidentally, I noticed that below the "weather.gov" text is a the next "National Weather Service" and that links to noaa.gov, which seems wrong. 😛 We probably need to change either the text or the link so they match.
- Search: Redundant "change location" AND "search for location" AND "search for location in search box"
  - Yes. I think this should be noted in the search design ticket #185. We can fiddle with it, but it doesn't seem like a good use of time right now to me. There's also a little bit of VO funkiness at play with the "search for location" and "search for location in search box" stuff. It's reading the label when you land on it, then when it gets to the input, it reads the associated label again. I believe this is normal and expected behavior, but we should definitely look into it.
- Current conditions: Consider skipping to “weather as of [Date][Time] + [Summary]”
  - Does this mean hiding the "widget" parts from screen readers? If so, that makes sense to me.
- All Icons don’t have alt text
  - Icons that are accompanied by and sitting next to descriptive text shouldn't have alt text, but they should have `alt=""`. However, we're not using `<img>` tags for these icons, so we can't set `alt` attributes at all. We are instead embedding the SVGs directly into the page. We're doing it that way because our SVGs have a white stroke, and the only way to change the stroke color in CSS is if you embed the SVG itself. You can't do it if you're using `<img>` tags. So... we can update all of our icons to have a black stroke and then use `<img>` tags and that would probably be perfectly fine. We can also play with replacing the icons entirely with blank DOM nodes that use [background masks](https://codepen.io/noahblon/post/coloring-svgs-in-css-background-images#css-masks-1), which would continue to let us change the stroke color in CSS, like if we wanted to support dark mode.
- Hourly forecast: navigates by each individual component (4PM, image, mostly cloudy, 2% chance, 46, ºF) should we group these so they're read together by hour?
  - I think the only way to do this would be have screenreader-only text, and then hide the rest from the screenreader, which would work pretty well, I think. 🤔 
- Hourly forecast: I’d like to be able to exit out of Hourly forecast easily and then go to Daily Forecast (without having to tab by component) - wrap in a div? (this might exist in the VO tool / be a possible human error)
  - I don't think we can do anything about this. I believe the way a user would do it would be to summon the list of headings/landmarks again and navigate to it from there.
- Hourly forecast: Temperature and ºF are not grouped to be read together
  - Probably need to make strategic-use of sr-only content here, too.

**Comment by greg-does-weather** [comment] 2023-12-08 22:00
Adding a note here for my future self.

On the icons, if we replace everything in the `<div class="icon" ..>` block with this, we'll get empty divs (so screen readers won't attempt to announce them) with *apparent* icons that will scale up or down to fit:

```html
<div
  style="
    background-color: black;
    mask-image: url(/icon.svg);
    mask-position: center;
    mask-repeat: no-repeat;
    mask-size: contain;
  "
  class="icon height-8 width-9">
</div>
```

**Comment by eric-gade** [comment] 2023-12-12 19:24
> All Icons don’t have alt text 
  
There is another option in addition to those @greg-does-weather outlined for providing accessible titles/descriptions to inline svgs: we can run a build script that turns each of our svg images into a corresponding twig template (ie template partials) that takes arguments. We can do this because SVGs are valid HTML.
  
So a hypothetical svg called "clouds.svg" that looks something like:
```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg  viewBox="0 0 50 50" width="50" height="50">
<!-- REST OF SVG HERE -->
</svg>
```
  
Would end up as a template file with the optional argument `title`, which we can use as follows:
```html
<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg  viewBox="0 0 50 50" width="50" height="50" aria-labelledby="icon-title">
<title id="icon-title">{{ title }}</title>
<!-- REST OF SVG HERE -->
</svg>
```
  
Then in other templates wherever we want to include the image, we do it as follows:
```twig
<!-- other twig stuff up here -->
{% include directory ~ "/path/to/svg/templates/cloud.html.twig" with { "title": "My accessible description" } %}
<!-- rest of enclosing twig template -->
```
  
The only downside I can see to doing it this way is that we actually need to generate unique ids for the `<title>` elements in each svg (if we want to be "correct" about html semantics), and would probably have to do that randomly or with uuid or something like that.

**Comment by partly-igor** [comment] 2023-12-12 20:09
That's a neat idea, I wonder if we could leverage the file names to generate the ids if we do want to use titles? I like that this approach could give us the option of providing the title for when we do want the icon announced or otherwise default to aria-hidden / non-focusable.  Another advantage this may have over the mask approach is being able to have multicolor icons in the future. 

I know this is not the issue, but  wanted to note that I'd be happy to export a set of the icons that are black if that would be helpful to you all – that's what I'm working with in Figma.

**Comment by eric-gade** [comment] 2023-12-12 21:15
@partly-igor 
> I wonder if we could leverage the file names to generate the ids if we do want to use titles?
  
We could use these as _part_ of the id, but we still need to generate a unique id for each occurrence of even the same svg image on the page.

**Comment by partly-igor** [comment] 2023-12-12 21:17
Ah, right, thank you for the clarification

**Comment by eric-gade** [comment] 2023-12-13 15:38
@partly-igor @greg-does-weather I have implemented an [example of the icon changes as a draft PR here](https://github.com/weather-gov/weather.gov/pull/531). Let me know what you think. For the moment, I'm going to move on to the other relevant items in this list.

**Comment by eric-gade** [comment] 2023-12-13 21:54
I will be updating the relevant points from @colinmurphy01 original list, with comments and annotations, here:
### Mac VoiceOver + Chrome
- [x] Beta Banner: Full website url is read aloud (consider hyperlinking weather.gov)
        _I believe this was addressed in #535 also_
- [x] Header: Logo + Weather.gov both have links, duplicative?
        _Addressed in #535_
- [ ] Search: Redundant "change location" AND "search for location" AND "search for location in search box"
- [ ] Current conditions: doesn’t  have a H2 header
- [ ] Current conditions: Consider skipping to “weather as of [Date][Time] + [Summary]”
- [x] All Icons don’t have alt text
       _As @greg-does-weather mentioned in an earlier comment, not all icons are required to have descriptive text. If their surrounding context contains nearby descriptive text, that does the job well enough (and on the location page I think this is the case just about everywhere). However, #531 addresses the ability to add descriptive text to our inline SVG images more easily._
- [x] Hourly forecast: navigates by each individual component (4PM, image, mostly cloudy, 2% chance, 46, ºF) should we group these so they're read together by hour?
       _See below_
- [x] Hourly forecast: I’d like to be able to exit out of Hourly forecast easily and then go to Daily Forecast (without having to tab by component) - wrap in a div? (this might exist in the VO tool / be a possible human error)
       _This capability is already there and depends on how the user navigates with the SR tools. However, this question prompted @partly-igor to make the suggestion that we use lists for these structures, which I agree with. This has been implemented in https://github.com/weather-gov/weather.gov/pull/536
- [ ] Hourly forecast: Temperature and ºF are not grouped to be read together
- [ ] Daily forecast: Repetition temperature reads “day will be high of “54” degrees 54º night will be low of 48ºF”

### Chrome Wave Extension
- [ ] No alt text in gov banner for flag
- [ ] Footer links are grouped in multiple <nav> elements with aria labels?

**Comment by greg-does-weather** [comment] 2023-12-14 01:11
Another approach for the icons would be to put them all into a single SVG sprite sheet and reference them via `<svg ...><use href="path.svg#icon_id" /></svg>`. That gives us the ability to style them with CSS, add arbitrary attributes, and exposes them as a separate resource that can be cached independently by middleware caches and end-user browsers.

**Comment by eric-gade** [comment] 2023-12-14 16:11
@greg-does-weather you know what? I think that's a much better way to organize this. It gives us more control over the outer svg element, which is what we ultimately need. I will probably update #531 to use a sheet instead. We will still want a script that compiles all known icons into a single sheet (so we can add/remove icons as needed).

**Closed** 2024-05-23 19:23 UTC
Labels: Design, Eng, Debt
