### ISSUE TITLE
Link the WFO page to the WFO's AFD page

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#1568] opened 2024-08-17 02:40 UTC
### Description

When the AFD tickets (#1526, #1528, #1527, #1529, #1530) are done, we need to update the WFO page so it links to the WFO's AFD page.

### Questions and Considerations

Where should the AFD link take people? We probably can't answer that completely until the AFD page is built, but we'll need to answer it before we can pick this up.

### Acceptance Criteria
- [ ] You can click the link and go where you think you're going

**Comment by colinmurphy01** [comment] 2024-08-26 16:15
Duplicate of #1617

**Comment by greg-does-weather** [comment] 2024-08-26 21:28
Not quite a duplicate!

**Closed** 2024-08-28 20:21 UTC
Labels: Eng
