### ISSUE TITLE
6-hourly precipitation amounts based on precipitation type

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#880] opened 2024-03-13 14:23 UTC
Right now in the 6-hourly precipitation amounts table, it displays liquid equivalent amounts of precipitation for all precipitation types.  So for this point (image below) where there is a Winter Storm Warning, it shows 0.8 inches of precipitation, which is probably equivalent to around 8 inches of snow (generally 10:1 ratio).  When there is snow, the forecast should display snow amounts, and potentially liquid/water equivalent amounts but de-emphasized.  Maybe an icon can clarify which amounts refer to which type of precipitation.  There are tricky times where there is a mix of rain and snow, or snow and sleet, etc.  The main types of precipitation that will be needed are rain, sleet, snow, and freezing rain.  I haven't ever seen sleet total amounts in weather.gov, but I think they exist.  

If this is a big level of effort, given that we are heading out of winter season, it's possible this isn't needed for MVP.

![Capture](https://github.com/weather-gov/weather.gov/assets/139174561/9701b3d4-8b7b-44ad-8366-0027a18ac880)

**Comment by colinmurphy01** [comment] 2024-04-15 13:20
@shadkeene Can you confirm that this is a duplicate of #987 and close it if it is?

**Closed** 2024-04-19 16:17 UTC
Labels: Iteration
