### ISSUE TITLE
Manual save of favorite locations. 

### ISSUE THREAD

**Issue by coreypieper** [weather-gov/weather.gov#1399] opened 2024-07-01 20:27 UTC
This ticket is meant to track desires expressed in external (TouchPoints) survey feedback to have the ability to manually save favorite forecast locations (like old mobile.weather.gov site).

**Comment by greg-does-weather** [comment] 2024-07-03 01:17
I think this will cover what's in #815 as well.

**Comment by colinmurphy01** [comment] 2024-07-15 16:33
Moving this to `Next` not a priority for the next couple milestones, but would likely be batched into a V2 Search Epic / Milestone

**Comment by colinmurphy01** [comment] 2024-10-29 19:27
duplicate of #815

**Closed by colinmurphy01** 2024-10-29 19:27 UTC
Labels: Scope
