### ISSUE TITLE
Diagram potential location-content relationships in CMS

### ISSUE THREAD

**Issue by cannandev** [weather-gov/weather.gov#22] opened 2023-05-30 19:03 UTC
We want to prototype how to correlate geographic location with content in a CMS. This is independent of how we define location (#90), though there is a little interplay between them.

```[tasklist]
### Tasks
- [ ] Discuss between Eng and Design on what questions and ideas exist for mapping content to a specific location + HMW do that conceptually?
- [ ] Determine how that could be prototyped in our 3 CMS options and added to CMS strategy for consideration?
```

**Comment by colinmurphy01** [comment] 2023-07-24 16:26
Deprioritize for Sprint 4 - this will come up during prototyping and will be influenced by design.

**Comment by colinmurphy01** [comment] 2023-09-12 13:02
@loganmeetsworld's architectual diagram

![Image](https://github.com/18F/weather.gov/assets/24654605/70408000-9cb7-49ae-a428-cefec3de0a73)


Questions

- Is the application subnet > Drupal instance the same as an Apache server on a traditional VM setup?
- Where do PHP config files live? Is memory storage controlled by an AWS setting? It normally lives in a php.ini file
- If the relational database fails, is the back up in a separate VPC? Or same subnet?

**Comment by colinmurphy01** [comment] 2023-09-14 20:03
I believe we can close this ticket as it was focused on the prototyping work. @cannandev can you confirm and close?

**Comment by colinmurphy01** [comment] 2023-10-03 15:45
@cannandev can you confirm the status of this ticket?

**Closed** 2023-10-13 15:56 UTC
Labels: :hourglass_flowing_sand: Task, Design, Eng
