### ISSUE TITLE
Should probably change degree wind direction to cardinal wind direction in "current conditions" component.

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#320] opened 2023-10-18 19:43 UTC
Wind direction on "current conditions" is in degrees.  Cardinal direction should be used for improved understanding. I think we should also spell out cardinal direction (East-Southeast vs. ESE).  This table can be used for reference.  I wonder if less detailed directions like North, Northeast, etc would be simpler and more understandable than North, North-northeast, Northeast, etc.

![Image](https://github.com/weather-gov/weather.gov/assets/139174561/ea112801-330a-4ed9-844c-2991a4a6f345)

**Comment by mgwalker** [comment] 2023-10-18 19:49
Is this a duplicate of #301? There's a pending fix in PR #302, but it only does the cardinal and ordinal directions (N, NE, E, SE, E, SW, W, NW), not the next level down (N, NNE, NE, ENE, E, etc.).

**Comment by shadkeene** [comment] 2023-10-18 19:57
Yes totally.  I think the 8 directions are fine vs. the very granular.  I'll close this ticket.  Was my first ticket...and a duplicate at that!

**Comment by shadkeene** [comment] 2023-10-18 19:57
Duplicate ticket.  closing.

**Comment by greg-does-weather** [comment] 2023-10-18 20:01
Just wait'll you have your first pull request and we break out the VSPR (very special pull request).

![vespa](https://media.giphy.com/media/R8vTqNwwiyGNzGcUY1/giphy.gif)

**Closed** 2023-10-24 14:45 UTC
Labels: Eng, Enhancement
