### ISSUE TITLE
Discovery & scoping: Event recaps

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1498] opened 2024-07-31 15:59 UTC
Deprioritized from the first stages of the Local Expertise epic, the goal here is to better understand the needs behind this content type and recommend an approach to scoping it. 

[Example](https://www.weather.gov/bou/20200606Derecho)

**Content type:** Hazardous event recaps
**Goals:** Provide comprehensive recaps of hazardous weather events and associated artifacts for insurance, resource allocation, education.
**Audience:** General public 
**Approach:** Compiled artifacts (text/image products, etc), organized in chronological order 

### Open questions from initial discovery ### 

Strategically: 
- Do these have to be categorized by WFO, or could it also be county/state?  
- What information (if any) is required vs nice to have? 
- Who uses this information, and for what? 
- What is the goal of having this information on the website? 
- Does that goal match the vision for weather.gov 2.0?

Tactically:
- How quickly do forecasters have to put this information together? 
- What file formats are most frequently included? 
- How is this content organized right now? Esp. multimedia files 

**Scoping document:** [link](https://docs.google.com/document/d/1yV7IrF3yllwpI-ceLAnABjQEp7YTW6fngHldqWQyhzU/edit?usp=sharing)

### Acceptance criteria ### 

- [x] The needs for this content are clearly understood and outlined
- [x] The process for obtaining and creating this content is understood
- [x] The types of artifacts that could be included are documented 
- [x] A recommendation for the scope of what this content should be on w.gov 2.0

**Comment by colinmurphy01** [comment] 2024-08-09 15:38
Duplicate of #1378 but some relevant documentation/comments are there for reference if needed.

**Comment by kmranjo** [comment] 2024-09-05 14:14
Most of this is mapped out now in the scoping doc added above. However, talking with Corey this week he flagged that we need to get a few others involved. We are working on setting up time with Aaron Treadway and others to try to get slightly more conclusive answers on the questions about target audience and purpose. 
In trying to plan ahead, I mapped out a few different possible approaches in the doc.

**Comment by kmranjo** [comment] 2024-09-12 16:51
Convo with the program leads yesterday was very helpful! I've updated the scoping doc and content model to reflect the information we got. Technically we still have a few questions outstanding that Corey is going to address with them via email, but I think we should be able to bring this to the POs next week.

**Comment by kmranjo** [comment] 2024-10-02 17:02
Chatted about this in PO sync. Product is aligned with approach, but recommends having some lo-fi visuals to bring to the conversation with champions. I'll work on mocking something up this week or next week depending on other priorities.

**Closed** 2024-10-29 14:19 UTC
Labels: Product, Content, Scope
