### ISSUE TITLE
Add Snow/Sleet precipitation amount forecasts to table and graph

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#987] opened 2024-04-01 15:44 UTC
User Story: I want to know how much it will rain, snow, sleet, freezing rain over the next 7 days.

Table
![Image](https://github.com/weather-gov/weather.gov/assets/24654605/649d705a-7556-488b-9234-c57b5dd36604)

Graph #1640 
![Screenshot 2024-09-06 at 11 44 16 AM](https://github.com/user-attachments/assets/427732e4-68ef-427a-b7ed-5f2366cb6c2d)

Considerations
- When there is a mix of precip types forecasted how is that communicated ([tool](https://digital.weather.gov/?zoom=3&lat=52.08769&lon=-110.77677&layers=F000BTTTFFTT&region=0&element=20&mxmz=false&barbs=false&subl=TFFFFF&units=english&wunits=nautical&coords=latlon&tunits=localt) for seeing where snow is in the US)
  - Example: 7.67 inches of snow, 1.016 QPF 
  - Hypothesis: display a given row (all of them) if there's a non-zero

**Comment by colinmurphy01** [comment] 2024-05-06 16:57
Deprioritizing due to seasonality and difficulty in testing with little/no snow happening around the country.

**Comment by colinmurphy01** [comment] 2024-08-26 16:40
#1189 is a dependency

**Comment by coreypieper** [comment] 2024-08-26 19:10
SME's confirmed this hypothesis for displaying: 

_We should display all available precip type accumulations when available (we have "quantitativePrecipitation", "iceAccumulation", and "snowfallAmount"). Since the "quantitativePrecipitation" is the liquid equivalent of whatever falls, we'd always want to display that, even if only non-liquid precip is predicted to fall in the same period. It's worth noting that this is also how the current hourly graph works on weather.gov._

**Comment by colinmurphy01** [comment] 2024-09-16 16:32
When picking up this redesign be mindful of also addressing use cases in #1145

**Comment by greg-does-weather** [comment] 2024-10-11 18:53
Closed by PR

**Closed by greg-does-weather** 2024-10-11 18:53 UTC
Labels: Design
